---
- name: Configure Oracle Linux 7.1 with WebLogic 12.2.1.3.0
  hosts: weblogic
  sudo: False
  #vars_files:
    # User defined variables for infrastructure
    #- infra-vars.yml
    # Common properties. You may not delete this
    #- wls-vars.yml
    # Infrastructure passwords
    #- secrets.yml
  roles:
    - role: linux-wls
    #- role: linux-jdk
    #- role: fmw-software
    #  sudo_user: '{{ oracle_user }}'
    #- role: fmw-domain
    #  sudo_user: '{{ oracle_user }}'
    #- role: node-manager
    #- role: start-admin-server
    #  sudo_user: '{{ oracle_user }}'