middleware_home: '/u01/wlsp/fmw12c/middleware/'
middleware_common_home: '{{ middleware_home }}/oracle_common'
domains_home: '/u01/wlsp/fmw12c/domains/'
applications_home: '{{ domain_home }}/applications'
mw_installer_folder: '/u01/wlsp/fmw12c/installer'
domain_home: '{{ domains_home }}/{{ domain_name }}'
nodemanager_home: '/u01/wlsp/fmw12c/nodemanager'
#nodemanager_home: '/u01/wlsp/fmw12c/domains/ClaroDomain'
weblogic_home: '{{ middleware_home }}/wlserver'
nodemanager_username: 'weblogic'
weblogic_admin: 'weblogic'
admin_server_name: 'AdminServer'
server_hostname: '{{ ansible_fqdn }}'