################################################################################
# ==> Tasks for configure Linux RedHat 7.4 ClaroChile
# ==> requirements for infrastructrure installation.
# ==> Supports version 12.2.1
# ==> author: Cristian Suarez
################################################################################


- name: Add repository ClaroChile
  command: rhnreg_ks --serverUrl=http://10.38.97.65/XMLRPC --activationkey=1-510df493c899849b3f4fd0b1202f5b7f --force 

- name: Instalar sysstat
  command: yum install sysstat --nogpgcheck -y

- name: Instalar htop
  command: yum install htop --nogpgcheck -y


- name: Instalar telnet
  command: yum install telnet --nogpgcheck -y

- name: Instalar bind-utils (nslookup)
  command: yum install bind-utils --nogpgcheck -y

- name: Instalar nmap
  command: yum install nmap --nogpgcheck -y

- name: Instalar ntp
  command: yum install ntp --nogpgcheck -y

- name: Verificar si el archivo existe cloud.cfg
  stat: path=/etc/cloud/cloud.cfg
  register: stat_result

- name: renombar cloud.cfg
  command: mv /etc/cloud/cloud.cfg /etc/cloud/cloud.cfg.old
  when: stat_result.stat.exists == True

- name: reboot host
  shell: ( sleep 3 && /sbin/reboot & )
  async: 0
  poll: 0

- name: Wait for the server to rebootp
  local_action: wait_for host="{{ansible_ssh_host}}" delay=15 state=started port="{{ansible_ssh_port}}" connect_timeout=10 timeout=180


- name: main | changing hostname to match inventory_hostname_short
  hostname:
    name: "{{ inventory_hostname_short }}"
  register: "hostname_status"
  become: true
  when: ansible_hostname != inventory_hostname_short

- name: main | restarting machine
  shell: /sbin/shutdown -r now "rebooting to complete hostname change"
  async: 1
  poll: 0
  ignore_errors: true
  become: true
  when: >
        (change_hostname_reboot is defined and
        change_hostname_reboot ) and
        hostname_status.changed

- name: main | waiting for server to come back
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
  vars:
    ansible_connection: local
  become: false
  when: >
        (change_hostname_reboot is defined and
        change_hostname_reboot ) and
        hostname_status.changed

- name: Modificar permiso hostname
  command: chattr +i /etc/hostname


- name: add lines network eth0
  lineinfile: 
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: '{{ item }}'
  with_items:
    - 'PEERDNS=no'
    - 'DOMAIN=clarochile.org'
    - 'NM_CONTROLLED=yes'
    - 'DNS1=10.38.4.171'
    - 'DNS2=10.38.4.172'

- name: add lines resolv.conf
  lineinfile: 
    dest: /etc/resolv.conf
    line: '{{ item }}'
  with_items:
    - 'search clarochile.org'
    - 'nameserver 10.38.4.171'
    - 'nameserver 10.38.4.172'



- name: Modificar permiso reslv.conf
  command: chattr +i /etc/resolv.conf
# Configure ntp.conf
- name: Configure ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644


- name: Disable SELinux
  selinux: state=disabled
- name: Disable Firewall Deamon (firewalld)
  service: name=firewalld state=stopped enabled=no



